name: Compile DTS Files
on: [push]
jobs:
  compile-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
      - name: Install DTC 
        run: sudo apt-get install device-tree-compiler
      - name: Create DTS Directory 
        run: |
          echo "DTS_OUTPUTPATH=$GITHUB_WORKSPACE/dts_out" >> "$GITHUB_ENV"
          if [[ ! -d $DTS_OUTPUTPATH ]]; then  
            mkdir -p $DTS_OUTPUTPATH  
            echo "创建DTB输出目录: $DTS_OUTPUTPATH !"  
          else  
            echo "DTB输出目录已存在: $DTS_OUTPUTPATH !"  
          fi 
      - name: Compile DTS to DTB
        id: Compile
        run: |
          ##编译dts
          [[ -d "dtb" ]] || mkdir dtb
          find . -name "*.dts" -exec sh -c 'dtc -I dts -O dtb -o $DTS_OUTPUTPATH/"${0%.dts}.dtb" "$0"' {} \;
          
      - name: Upload the Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # 动态获取当前tag名称
          artifacts: $DTS_OUTPUTPATH
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 自动编译测试
