name: Compile DTS Files
on: [push]
jobs:
  compile-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
      - name: Install DTC 
        run: sudo apt-get install device-tree-compiler
      - name: Create DTS Directory 
        env:
          DTS_OUTPUTPATH: $GITHUB_WORKSPACE/dts_out
        run: |
          
          if [[ ! -d ${{ env.DTS_OUTPUTPATH }} ]]; then  
            mkdir -p ${{ env.DTS_OUTPUTPATH }}
            echo "创建DTB输出目录: ${{ env.DTS_OUTPUTPATH }} !"  
          else  
            echo "DTB输出目录已存在: ${{ env.DTS_OUTPUTPATH }} !"  
          fi 
      - name: Compile DTS to DTB
        id: Compile
        run: |
          ##编译dts
          ##find . -name "*.dts" -exec sh -c 'echo "正在编译 ${{ env.DTS_OUTPUTPATH }}/"${0%.dts}.dtb ..." && dtc -I dts -O dtb -o  ${{ env.DTS_OUTPUTPATH }}/"${0%.dts}.dtb" "$0"' {} \;
          TARGET_DIR="./dts"  # 目标目录路径
          # 遍历目录下所有文件（包含子目录）
          find "$TARGET_DIR" -type f -name "*.dts" -print0 | while IFS= read -r -d $'\0' file; do
            in_dts_file=$(basename "$file")
            out_dts_file=${{ env.DTS_OUTPUTPATH }}/${in_dts_file%.*}.dtb
            echo "正在生成: $out_dts_file"
          done
      - name: Upload the Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  # 动态获取当前tag名称
          artifacts:  ${{ env.DTS_OUTPUTPATH }}
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ### 自动编译测试
