name: Compile DTS Files
on: [push]
jobs:
  compile-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
      - name: Install DTC
        run: sudo apt-get install device-tree-compiler
      - name: Compile DTS to DTB
        run: find . -name "*.dts" -exec sh -c 'dtc -I dts -O dtb -o "${0%.dts}.dtb" "$0"' {} \;
      - name: Upload artifacts
        uses: actions/upload-artifact
        with:
          name: dtb-files
          path: "**/*.dtb"
